# -*- coding: utf-8 -*-
"""Screen Time Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIDeslaclzX4DXk4CqIlLFtyM88cKKPy

## 🤳Screen Time Analysis with Python

### Screen Time Analysis lets you know how much time you spend on what kind of applications and websites using your device. And screen time analysis gives a visual report of the same.

#### Screen Time Analysis is the task of analyzing and creating a report on which applications and websites are used by the user for how much time.

Apple devices have one of the best ways of creating a screen time report.

Features in the data:

- Date: Date of the record
- Usage: Number of times the user used the smartphone in a day
- Notifications: Number of notifications the user received in a day
- Times opened: Number of times the app was opened by the user
- App: The app that was opened by the user

Analyze the screen time of the user to find relationships between the usage of the smartphone and factors like notifications and apps used by the user.
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

data = pd.read_csv("Screentime-App-Details.csv")
print(data.head())

"""Now let’s have a look if the dataset has any null values or not:"""

data.isnull().sum()

"""The dataset doesn’t have any null values. Now let’s have a look at the descriptive statistics of the data:"""

print(round(data.describe()))

"""Start with analyzing the screen time of the user. First, look at the amount of **usage** of the apps:"""

figure = px.bar(data_frame=data,
                x = "Date",
                y = "Usage",
                color="App",
                title="Usage")
figure.show()

"""Take a look at the number of **notifications** from the apps:"""

figure = px.bar(data_frame=data,
                x = "Date",
                y = "Notifications",
                color="App",
                title="Notifications")
figure.show()

"""Take a look at the number of times the apps opened:"""

figure = px.bar(data_frame=data,
                x = "Date",
                y = "Times opened",
                color="App",
                title="Times Opened")
figure.show()

"""We generally use our smartphones when we get notified by any app. So take a look at the relationship between the number of notifications and the amount of usage:"""

figure = px.scatter(data_frame = data,
                    x="Notifications",
                    y="Usage",
                    size="Notifications",
                    trendline="ols",
                    title = "Relationship Between Number of Notifications and Usage")
figure.show()

"""There is a linear relationship between the number of notifications and the amount of usage.Meaning that more notifications result in more use of smartphones.

#### Summary
So this is how we can analyze the screen time of a user using the Python programming language.

Screen Time Analysis is the task of analyzing and creating a report on which applications and websites are used by the user and for how much time.

Thank you for reading ✌️

`Data Source Credit: Ruchi Bhatia | Kaggle`
"""